# Generated by Django 5.1.6 on 2025-11-28 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='page_number',
            field=models.IntegerField(blank=True, help_text='Slide/Page number reference', null=True),
        ),
    ]
