# Generated by Django 5.1.6 on 2025-11-29 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_question_page_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='nature',
            field=models.CharField(choices=[('Teorica', 'Teorica'), ('Pratica', 'Pratica')], default='Teorica', max_length=20),
        ),
    ]
